In [1]:
pip install kafka-python

Collecting kafka-python
  Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
     ------------------------------------ 246.5/246.5 kB 718.1 kB/s eta 0:00:00
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from kafka import KafkaProducer
from time import sleep
from json import dumps 
import json

In [2]:
# Connect kafka producer to AWS server with encoder 'utf-8'
producer = KafkaProducer(bootstrap_servers=['43.206.231.106:9092'], #change ip here
                         value_serializer=lambda x: 
                         dumps(x).encode('utf-8'))

In [3]:
# For test whether producer can send to consumer ot not
producer.send('stock_market_demo', value={'name':'Jeny'})

In [6]:
# Now read csv from our directory using pandas
df = pd.read_csv("D:/ITStep/Apache_Kafka/stock-market-kafka-data-engineering-project-main/indexProcessed.csv")
df.head(500)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,12/31/1986,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0,333.879006
1,HSI,1/2/1987,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0,330.213013
2,HSI,1/5/1987,2552.399902,2552.399902,2552.399902,2552.399902,2552.399902,0,331.811987
3,HSI,1/6/1987,2583.899902,2583.899902,2583.899902,2583.899902,2583.899902,0,335.906987
4,HSI,1/7/1987,2607.100098,2607.100098,2607.100098,2607.100098,2607.100098,0,338.923013
5,HSI,1/8/1987,2603.300049,2603.300049,2603.300049,2603.300049,2603.300049,0,338.429006
6,HSI,1/9/1987,2561.699951,2561.699951,2561.699951,2561.699951,2561.699951,0,333.020994
7,HSI,1/12/1987,2614.899902,2614.899902,2614.899902,2614.899902,2614.899902,0,339.936987
8,HSI,1/13/1987,2590.800049,2590.800049,2590.800049,2590.800049,2590.800049,0,336.804006
9,HSI,1/14/1987,2578.199951,2578.199951,2578.199951,2578.199951,2578.199951,0,335.165994
10,HSI,1/15/1987,2559.100098,2559.100098,2559.100098,2559.100098,2559.100098,0,332.683013
11,HSI,1/16/1987,2542.600098,2542.600098,2542.600098,2542.600098,2542.600098,0,330.538013
12,HSI,1/19/1987,2460.500000,2460.500000,2460.500000,2460.500000,2460.500000,0,319.865000
13,HSI,1/20/1987,2449.899902,2449.899902,2449.899902,2449.899902,2449.899902,0,318.486987
14,HSI,1/21/1987,2533.899902,2533.899902,2533.899902,2533.899902,2533.899902,0,329.406987
15,HSI,1/22/1987,2536.899902,2536.899902,2536.899902,2536.899902,2536.899902,0,329.796987
16,HSI,1/23/1987,2499.399902,2499.399902,2499.399902,2499.399902,2499.399902,0,324.921987
17,HSI,1/26/1987,2484.399902,2484.399902,2484.399902,2484.399902,2484.399902,0,322.971987
18,HSI,1/27/1987,2524.000000,2524.000000,2524.000000,2524.000000,2524.000000,0,328.120000
19,HSI,1/28/1987,2553.300049,2553.300049,2553.300049,2553.300049,2553.300049,0,331.929006
20,HSI,2/2/1987,2585.199951,2585.199951,2585.199951,2585.199951,2585.199951,0,336.075994
21,HSI,2/3/1987,2606.399902,2606.399902,2606.399902,2606.399902,2606.399902,0,338.831987
22,HSI,2/4/1987,2636.600098,2636.600098,2636.600098,2636.600098,2636.600098,0,342.758013
23,HSI,2/5/1987,2672.399902,2672.399902,2672.399902,2672.399902,2672.399902,0,347.411987
24,HSI,2/6/1987,2673.600098,2673.600098,2673.600098,2673.600098,2673.600098,0,347.568013
25,HSI,2/9/1987,2713.699951,2713.699951,2713.699951,2713.699951,2713.699951,0,352.780994
26,HSI,2/10/1987,2694.899902,2694.899902,2694.899902,2694.899902,2694.899902,0,350.336987
27,HSI,2/11/1987,2739.500000,2739.500000,2739.500000,2739.500000,2739.500000,0,356.135000
28,HSI,2/12/1987,2754.699951,2754.699951,2754.699951,2754.699951,2754.699951,0,358.110994
29,HSI,2/13/1987,2740.500000,2740.500000,2740.500000,2740.500000,2740.500000,0,356.265000
30,HSI,2/16/1987,2766.100098,2766.100098,2766.100098,2766.100098,2766.100098,0,359.593013
31,HSI,2/17/1987,2792.100098,2792.100098,2792.100098,2792.100098,2792.100098,0,362.973013
32,HSI,2/18/1987,2801.500000,2801.500000,2801.500000,2801.500000,2801.500000,0,364.195000
33,HSI,2/19/1987,2775.800049,2775.800049,2775.800049,2775.800049,2775.800049,0,360.854006
34,HSI,2/20/1987,2827.399902,2827.399902,2827.399902,2827.399902,2827.399902,0,367.561987
35,HSI,2/23/1987,2879.000000,2879.000000,2879.000000,2879.000000,2879.000000,0,374.270000
36,HSI,2/24/1987,2848.199951,2848.199951,2848.199951,2848.199951,2848.199951,0,370.265994
37,HSI,2/25/1987,2873.600098,2873.600098,2873.600098,2873.600098,2873.600098,0,373.568013
38,HSI,2/26/1987,2843.600098,2843.600098,2843.600098,2843.600098,2843.600098,0,369.668013
39,HSI,2/27/1987,2877.899902,2877.899902,2877.899902,2877.899902,2877.899902,0,374.126987
40,HSI,3/2/1987,2894.300049,2894.300049,2894.300049,2894.300049,2894.300049,0,376.259006
41,HSI,3/3/1987,2939.100098,2939.100098,2939.100098,2939.100098,2939.100098,0,382.083013
42,HSI,3/4/1987,2890.899902,2890.899902,2890.899902,2890.899902,2890.899902,0,375.816987
43,HSI,3/5/1987,2798.399902,2798.399902,2798.399902,2798.399902,2798.399902,0,363.791987
44,HSI,3/6/1987,2798.600098,2798.600098,2798.600098,2798.600098,2798.600098,0,363.818013
45,HSI,3/9/1987,2820.399902,2820.399902,2820.399902,2820.399902,2820.399902,0,366.651987
46,HSI,3/10/1987,2731.100098,2731.100098,2731.100098,2731.100098,2731.100098,0,355.043013
47,HSI,3/11/1987,2760.899902,2760.899902,2760.899902,2760.899902,2760.899902,0,358.916987
48,HSI,3/12/1987,2750.100098,2750.100098,2750.100098,2750.100098,2750.100098,0,357.513013

In [ ]:
# send message that read from pandas to consumer record by record, and sleep 1 second so not to overload server to consumer
while True:
    stocks = df.sample(1).to_dict(orient='records')[0]
    producer.send('stock_market_demo', value=stocks)
    sleep(1)

In [4]:
# restart all the values in consumer
producer.flush()